{%- from "kubernetes/map.jinja" import master with context %}
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: 'Heapster'
  name: heapster
  namespace: kube-system
spec:
{%- if master.network.engine != 'opencontrail' %}
  selector: 
    k8s-app: heapster
{%- endif %}
  ports:
  - port: 80
    targetPort: 8082
